name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step to copy entrypoint.sh before building 18
      - name: Prepare for Node.js 18 build
        run: cp entrypoint.sh 18/

      - name: Build and push Node.js 18
        uses: docker/build-push-action@v2
        with:
          context: ./18
          push: true
          tags: ghcr.io/ar4kiara/eggs:18
          no-cache: true

      # Step to copy entrypoint.sh before building 20
      - name: Prepare for Node.js 20 build
        run: cp entrypoint.sh 20/

      - name: Build and push Node.js 20
        uses: docker/build-push-action@v2
        with:
          context: ./20
          push: true
          tags: ghcr.io/ar4kiara/eggs:20
          no-cache: true

      # Step to copy entrypoint.sh before building 22
      - name: Prepare for Node.js 22 build
        run: cp entrypoint.sh 22/

      - name: Build and push Node.js 22
        uses: docker/build-push-action@v2
        with:
          context: ./22
          push: true
          tags: ghcr.io/ar4kiara/eggs:22
          no-cache: true

      # Step to copy entrypoint.sh before building 23
      - name: Prepare for Node.js 23 build
        run: cp entrypoint.sh 23/

      - name: Build and push Node.js 23
        uses: docker/build-push-action@v2
        with:
          context: ./23
          push: true
          tags: ghcr.io/ar4kiara/eggs:23
          no-cache: true

      # Step to copy entrypoint.sh before building 24
      - name: Prepare for Node.js 24 build
        run: cp entrypoint.sh 24/

      - name: Build and push Node.js 24
        uses: docker/build-push-action@v2
        with:
          context: ./24
          push: true
          tags: ghcr.io/ar4kiara/eggs:24
          no-cache: true

      # Alpine versions
      - name: Prepare for Node.js 18 Alpine build
        run: cp entrypoint.sh 18-alpine/

      - name: Build and push Node.js 18 Alpine
        uses: docker/build-push-action@v2
        with:
          context: ./18-alpine
          push: true
          tags: ghcr.io/ar4kiara/eggs:18-alpine
          no-cache: true

      - name: Prepare for Node.js 20 Alpine build
        run: cp entrypoint.sh 20-alpine/

      - name: Build and push Node.js 20 Alpine
        uses: docker/build-push-action@v2
        with:
          context: ./20-alpine
          push: true
          tags: ghcr.io/ar4kiara/eggs:20-alpine
          no-cache: true

      - name: Prepare for Node.js 22 Alpine build
        run: cp entrypoint.sh 22-alpine/

      - name: Build and push Node.js 22 Alpine
        uses: docker/build-push-action@v2
        with:
          context: ./22-alpine
          push: true
          tags: ghcr.io/ar4kiara/eggs:22-alpine
          no-cache: true

      - name: Prepare for Node.js 23 Alpine build
        run: cp entrypoint.sh 23-alpine/

      - name: Build and push Node.js 23 Alpine
        uses: docker/build-push-action@v2
        with:
          context: ./23-alpine
          push: true
          tags: ghcr.io/ar4kiara/eggs:23-alpine
          no-cache: true

      - name: Prepare for Node.js 24 Alpine build
        run: cp entrypoint.sh 24-alpine/

      - name: Build and push Node.js 24 Alpine
        uses: docker/build-push-action@v2
        with:
          context: ./24-alpine
          push: true
          tags: ghcr.io/ar4kiara/eggs:24-alpine
          no-cache: true

      # Ubuntu versions
      - name: Prepare for Node.js 18 Ubuntu build
        run: cp entrypoint.sh 18-ubuntu/

      - name: Build and push Node.js 18 Ubuntu
        uses: docker/build-push-action@v2
        with:
          context: ./18-ubuntu
          push: true
          tags: ghcr.io/ar4kiara/eggs:18-ubuntu
          no-cache: true

      - name: Prepare for Node.js 20 Ubuntu build
        run: cp entrypoint.sh 20-ubuntu/

      - name: Build and push Node.js 20 Ubuntu
        uses: docker/build-push-action@v2
        with:
          context: ./20-ubuntu
          push: true
          tags: ghcr.io/ar4kiara/eggs:20-ubuntu
          no-cache: true

      - name: Prepare for Node.js 22 Ubuntu build
        run: cp entrypoint.sh 22-ubuntu/

      - name: Build and push Node.js 22 Ubuntu
        uses: docker/build-push-action@v2
        with:
          context: ./22-ubuntu
          push: true
          tags: ghcr.io/ar4kiara/eggs:22-ubuntu
          no-cache: true

      - name: Prepare for Node.js 23 Ubuntu build
        run: cp entrypoint.sh 23-ubuntu/

      - name: Build and push Node.js 23 Ubuntu
        uses: docker/build-push-action@v2
        with:
          context: ./23-ubuntu
          push: true
          tags: ghcr.io/ar4kiara/eggs:23-ubuntu
          no-cache: true

      - name: Prepare for Node.js 24 Ubuntu build
        run: cp entrypoint.sh 24-ubuntu/

      - name: Build and push Node.js 24 Ubuntu
        uses: docker/build-push-action@v2
        with:
          context: ./24-ubuntu
          push: true
          tags: ghcr.io/ar4kiara/eggs:24-ubuntu
          no-cache: true 
          
